# DockerCompose
# Build a Docker Services using docker compose 
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Services
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Developers Subscription(10c93541-a379-49d2-a612-8d3e1669dc02)'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        nopIfNoDockerComposeFile: true