version: "3.6"

services:
    wallet:
        container_name: wallet_user
        image: wallet_user
        build:
            context: ./images/wallet
        networks:
            - node
        volumes:
            - ./app/wallet:/srv/app/api
        command: ["sh", "-c", "/startup.sh"]
    walletdb:
        container_name: wallet_db
        build: ./images/walletdb
        image: wallet_db_001
        hostname: walletdb-docker
        networks:
            - node
        ports:
            - "5552:5432"
        expose:
            - 5432
        volumes:
            - "walletdb:/var/lib/postgresql/data"

    # node:
    #     container_name: chain_node
    #     image: chain_node_001
    #     build:
    #         context: ./images/node
    #     expose:
    #         - 8000
    #     ports:
    #         - "80:80"
    #     networks:
    #         - node
    #         - miner
    #     volumes:
    #         - ./app/node:/srv/app/api
    #     command: ["sh", "-c", "/startup.sh"]
    # nodedb:
    #     container_name: node_db
    #     build: ./images/nodedb
    #     image: node_db_001
    #     hostname: nodedb-docker
    #     networks:
    #         - node
    #     ports:
    #         - "5532:5432"
    #     expose:
    #         - 5432
    #     volumes:
    #         - "nodedb:/var/lib/postgresql/data"

    # miner:
    #     container_name: chain_miner_001a
    #     image: chain_miner
    #     build:
    #         context: ./images/miner
    #     networks:
    #         - node
    #         - miner
    #     volumes:
    #         - ./app/miner:/srv/app/api
    #     command: ["sh", "-c", "/startup.sh"]
    # minerdb:
    #     container_name: miner_db
    #     build: ./images/minerdb
    #     image: miner_db_001
    #     hostname: minerdb-docker
    #     networks:
    #         - miner
    #     ports:
    #         - "5542:5432"
    #     expose:
    #         - 5432
    #     volumes:
    #         - "minerdb:/var/lib/postgresql/data"

    wallet:
        container_name: wallet_user
        image: wallet_user
        env_file:
            - .walletenv
        build:
            context: ./images/wallet
        # expose:
        #     - 8080
        # ports:
        #     - "80:8080"
        networks:
            - node
        volumes:
            - ./app/wallet:/srv/app/api
        command: ["sh", "-c", "/startup.sh"]
    walletdb:
        container_name: wallet_db
        build: ./images/walletdb
        image: wallet_db_001
        hostname: walletdb-docker
        env_file:
            - .walletenv
        networks:
            - node
        ports:
            - "5552:5432"
        expose:
            - 5432
        volumes:
            - "walletdb:/var/lib/postgresql/data"

networks:
    node: null
    # miner: null

volumes:
    # minerdb: null
    # nodedb: null
    walletdb: null
