name: Blockchain wallet build and test

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build environment and run unittests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Test path
        run: ls -la
      - name: Setup python requirements
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel black

      - name: Install dependencies
        run: python3 install -r images/wallet/config/requirements.txt

      - name: Run keymanager test
        run: python3 app/wallet/tests/testkeymanager.py
